[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
paths = ["."]
defaultToBase = true
ignoreEmptyStrings = true
unstripped = false

[update.code]
codePaths = ["."]
localizablePaths = ["BeagleIM/localization"]
defaultToKeys = true
additive = true
unstripped = false
plistArguments = true

[update.normalize]
paths = ["."]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["."]
duplicateKeys = true
emptyValues = true
